### ISSUE TITLE
Cert validation behaviour change in 2.2.0

### ISSUE THREAD

**Issue by will118** [rustls/pemfile#59]
I've noticed a change in behaviour with the following:

```rust
fn main() {
    let cert = "-----BEGIN CERTIFICATE-----\nINVALID\n-----END CERTIFICATE-----";
    let cert = rustls_pemfile::certs(&mut cert.as_bytes())
        .next()
        .unwrap()
        .unwrap();
    dbg!(cert);
}
```

```toml
[package]
name = "bad-cert"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls-pemfile = "=2.1.2"
# rustls-pemfile = "=2.2.0"
```

In `2.1.2` I see:

```
Custom { kind: InvalidData, error: "InvalidLastSymbol(6, 68)" }
```

but in `2.2.0` I get:
```
[src/main.rs:7:5] cert = CertificateDer(
    0x20d5402c80,
)
```

I'm not confident what the docs mean by:

> Filters out any PEM sections that are not certificates and yields errors if a problem occurs while trying to extract a certificate.

...but regardless the change surprised me and was caught by a test.

Is it expected?
